regions:
- us-east-1
- sa-east-1
- global

account-blacklist:
- "869122752574" # production

resource-types:
  # don't nuke
  excludes:
  - EC2VPC
  - EC2VPCEndpoint
  - EC2Subnet
  - EC2TGW
  - EC2TGWAttachment
  - EC2InternetGateway
  - EC2InternetGatewayAttachment
  - EC2NATGateway
  - EC2NetworkACL
  - EC2RouteTable
  - EC2VPCEndpointServiceConfiguration
  - EC2VPCPeeringConnection
  - EC2VPNConnection
  - EC2DHCPOption
  - EC2VPNGateway
  - EC2VPNGatewayAttachment
  - CloudTrailTrail
  - SNSSubscription

accounts:
  "000000000000":
    filters:
      ConfigServiceConfigurationRecorder:
      - "aws-controltower-BaselineConfigRecorder"
      CloudFormationStack:
      - property: Name
        type: glob
        value: "StackSet-AWSControlTowerBP-*"
      - property: Name
        type: glob
        value: "StackSet-*"
      CloudWatchLogsLogGroup:
      - property: Name
        type: glob
        value: "AWSControlTowerBP*"
      - property: Name
        type: exact
        value: "aws-controltower/CloudTrailLogs"
      CloudWatchEventsRule:
      - "Rule: aws-controltower-ConfigComplianceChangeEventRule"
      - "Rule: Sandbox-MonitoringEventRule"
      CloudWatchEventsTarget:
      - "Rule: aws-controltower-ConfigComplianceChangeEventRule"
      - "Rule: Sandbox-MonitoringEventRule"
      SNSTopic:
      - "TopicARN: arn:aws:sns:us-east-1:000000000000:aws-controltower-SecurityNotifications"
      - "TopicARN: arn:aws:sns:us-east-1:000000000000:Sandbox-SNSTopic"
      - "TopicARN: arn:aws:sns:sa-east-1:000000000000:Sandbox-SNSTopic"
      ConfigServiceDeliveryChannel:
      - "aws-controltower-BaselineConfigDeliveryChannel"
      IAMRole:
      - "RoleForLambdaFullAccess"
      - "aws-controltower-AdministratorExecutionRole"
      - "aws-controltower-CloudWatchLogsRole"
      - "aws-controltower-ConfigRecorderRole "
      - "aws-controltower-ForwardSnsNotificationRole"
      - "aws-controltower-ReadOnlyExecutionRole"
      - "AWSControlTowerExecution"
      - "AWSControlTower_VPCFlowLogsRole"
      - "RoleForCodeBuildSandbox"
      - "RoleForLambdaAccessResources"
      - "RoleForStepFunctionSandboxAccount"
      SFNStateMachine:
      - "arn:aws:states:us-east-1:000000000000:stateMachine:StepFunctionMonitoring"
      - "arn:aws:states:sa-east-1:000000000000:stateMachine:StepFunctionMonitoring"
      CodeBuildProject:
      - "AccountNuker-List"
      - "AccountNuker-Delete"
      LambdaFunction:
      - property: Name
        type: exact
        value: "MonitoringFuction"
      - property: Name
        type: exact
        value: "DeleteAccount"
      - property: Name
        type: exact
        value: "MissingDaysFunction"
      - property: Name
        type: exact
        value: "ListResources"
      - property: Name
        type: exact
        value: "ExecuteCWE"
      SSMParameter:
      - "account_id"
      - "account_days"
      - "account_initial"
      
        
        
        
        
      