regions:
- us-east-1
- sa-east-1
- global

account-blacklist:
- "869122752574" # production

resource-types:
  # don't nuke
  excludes:
  - EC2VPC
  - EC2VPCEndpoint
  - EC2Subnet
  - EC2TGW
  - EC2TGWAttachment
  - EC2InternetGateway
  - EC2InternetGatewayAttachment
  - EC2NATGateway
  - EC2NetworkACL
  - EC2RouteTable
  - EC2VPCEndpointServiceConfiguration
  - EC2VPCPeeringConnection
  - EC2VPNConnection
  - EC2DHCPOption
  - EC2VPNGateway
  - EC2VPNGatewayAttachment
  - CloudTrailTrail
  - SNSSubscription

accounts:
  "000000000000":
    filters:

      CloudFormationStack:
      - property: Name
        type: glob
        value: "StackSet-AWSControlTowerBP-*"
      - property: Name
        type: glob
        value: "StackSet-Stack*"
      CloudWatchLogsLogGroup:
      - property: Name
        type: glob
        value: "AWSControlTowerBP*"
      - property: Name
        type: exact
        value: "aws-controltower/CloudTrailLogs"
      CloudWatchEventsRule:
      - property: Name
        type: exact
        value: "aws-controltower-ConfigComplianceChangeEventRule"
      - property: Name
        type: exact
        value: "Sandbox-MonitoringEventRule"
      CloudWatchEventsTarget:
       - property: Name
         type: glob
         value: "Compliance-Change-Topic"
       - property: Name
         type: glob
         value: "aws-controltower*"
      SNSTopic:
      - property: Name
        type: exact
        value: "aws-controltower-SecurityNotifications"
      - property: Name
        type: exact
        value: "arn:aws:sns:us-east-1:000000000000:Sandbox-SNSTopic "
      ConfigServiceConfigurationRecorder:
      - property: Name
        type: contains
        value: "aws-controltower-BaselineConfigRecorder"
      ConfigServiceDeliveryChannel:
      - property: Name
        type: contains
        value: "aws-controltower-BaselineConfigDeliveryChannel"
      IAMRole:
      - property: Name
        type: glob
        value: "aws-controltower-*"
      - property: Name
        type: glob
        value: "AWSControlTower*" 
      - property: Name
        type: glob
        value: "AWSReservedSSO*"
      - property: Name
        type: exact
        value: "RoleForStepFunctionSandboxAccount"
      - property: Name
        type: contains
        value: "RoleForCodeBuildSandbox"
      - property: Name
        type: exact
        value: "RoleForLambdaFullAccess"
      SFNStateMachine:
      - property: Name
        type: exact
        value: "StepFunctionMonitoring"
      CodeBuildProject:
      - property: Name
        type: exact
        value: "AccountNuker-List"
      - property: Name
        type: exact
        value: "AccountNuker-Delete"
      LambdaFunction:
      - property: Name
        type: exact
        value: "MonitoringFuction"
      - property: Name
        type: exact
        value: "DeleteAccount"
      - property: Name
        type: exact
        value: "MissingDaysFunction"
      - property: Name
        type: exact
        value: "ListResources"
      - property: Name
        type: exact
        value: "ExecuteCWE"
      SSMParameter:
      - property: Name
        type: exact
        value: "account_id"
      - property: Name
        type: exact
        value: "account_days"
      - property: Name
        type: exact
        value: "account_initial"
      
        
        
        
        
      